#fisier folosit pentru compilarea serverului&clientului TCP concurent

all:
	gcc TCP_Client.c -o TCP_Client
	gcc TCP_Server.c -o TCP_Server
	gcc populate.c -o populate
clean:
	rm -f *~_Client _Server populate
